### ISSUE TITLE
Create a json file for generic responses

### ISSUE THREAD

**Issue by wambu-i** [wambu-i/Jumuiya#7]
Repeated and generic messages (eg introductory, language choosing, menus) should ideally pulled from a central resource. A json file is easily created and parsed making it suitable for this stage of the project.

Mentor @wambu-i

**Comment by XavierMichael** [comment]
`import json


x = '{ "message":"Kenya Nchi Yetu !I am a tool which provides accurate articles and resources for your political and civic empowerment.You will be also be able to find objective  and impartial articles on all political issues in Kenya.Welcome","language":{"options":["Kiswahili","English","French","Italian","German"]}}'

y = json.loads(x)


print(y["message"])
print(y["language"]["options"])`

**Comment by wambu-i** [comment]
@XavierMichael download git for Windows [here](https://git-scm.com/download/win) and install it.

After installation, open a command prompt window and clone the repository:

`git clone https://github.com/wambu-i/Jumuiya.git`.

Then go into the cloned directory:

`cd Jumuiya`

Save the above responses in a file `responses.json`.

Then:

`git checkout -b issue-7-responses`

`git add responses.json`

`git commit -m "Add responses file for generic responses - resolves #7"`

`git push origin issues-7-responses`.
